# Generated by Django 5.0.2 on 2024-02-17 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_alter_user_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_2",
            field=models.CharField(blank=True, max_length=20, verbose_name="Phone 2"),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_wholesale",
            field=models.BooleanField(default=False, verbose_name="حساب جملة"),
        ),
    ]
