# Generated by Django 5.0.2 on 2024-02-18 01:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_user_phone_2_alter_user_is_wholesale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                choices=[
                    ("al_anbar", "الأنبار"),
                    ("al_basra", "البصرة"),
                    ("al_muthanna", "المثنى"),
                    ("an_najaf", "النجف"),
                    ("al_qadisiyah", "القادسية"),
                    ("al_sulaymaniyah", "السليمانية"),
                    ("babil", "بابل"),
                    ("baghdad", "بغداد"),
                    ("dhi_qar", "ذي قار"),
                    ("dyala", "ديالى"),
                    ("dohuk", "دهوك"),
                    ("erbil", "اربيل"),
                    ("karbala", "كربلاء"),
                    ("kirkuk", "كركوك"),
                    ("maysan", "ميسان"),
                    ("ninawa", "نينوى"),
                    ("salah_ad_din", "صلاح الدين"),
                    ("wasit", "واسط"),
                ],
                max_length=50,
                verbose_name="City",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                choices=[("iraq", "العراق")],
                max_length=50,
                verbose_name="Country",
            ),
        ),
    ]
