# Generated by Django 5.0.2 on 2024-02-18 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_alter_user_city_alter_user_country"),
    ]

    operations = [
        migrations.CreateModel(
            name="WholesaleUserType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Title")),
                (
                    "negative_limit",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Negative Limit"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="wholesale_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wholesale_types",
                related_query_name="wholesale_type",
                to="authentication.wholesaleusertype",
            ),
        ),
    ]
