# Generated by Django 5.0.2 on 2024-02-18 20:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0008_user_wallet_balance_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("deposit", "ايداع"), ("order", "طلب")],
                max_length=50,
                verbose_name="Transaction Type",
            ),
        ),
    ]
