# Generated by Django 5.0.2 on 2024-02-18 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_alter_transaction_transaction_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="is_wholesale",
        ),
    ]
