# Generated by Django 5.0.2 on 2024-03-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_remove_user_is_wholesale"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=0, max_digits=26, verbose_name="Amount"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="wallet_balance",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=26,
                verbose_name="Wallet Balance",
            ),
        ),
        migrations.AlterField(
            model_name="wholesaleusertype",
            name="negative_limit",
            field=models.DecimalField(
                decimal_places=0, max_digits=26, verbose_name="Negative Limit"
            ),
        ),
    ]
