# Generated by Django 4.2.13 on 2025-01-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "authentication",
            "0011_alter_transaction_amount_alter_user_wallet_balance_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hidden",
            field=models.BooleanField(default=True, verbose_name="Hidden"),
        ),
    ]
