# Generated by Django 4.2.13 on 2025-01-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0012_user_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="hidden",
            field=models.BooleanField(default=False, verbose_name="Hidden"),
        ),
    ]
