# Generated by Django 4.1 on 2022-08-13 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-id"], "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="orderline",
            options={"ordering": ["id"], "verbose_name_plural": "Order Lines"},
        ),
        migrations.AlterModelOptions(
            name="supportticket",
            options={"ordering": ["-id"], "verbose_name_plural": "Support Tickets"},
        ),
    ]
