# Generated by Django 4.1 on 2022-11-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_alter_order_options_alter_orderline_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_wholesale",
            field=models.BooleanField(default=False),
        ),
    ]
