# Generated by Django 4.1 on 2022-11-25 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_is_wholesale"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_no",
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
