# Generated by Django 4.1 on 2022-11-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_order_order_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_no",
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
