# Generated by Django 4.1 on 2022-11-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_alter_order_order_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address_2",
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(
                choices=[
                    ("al_anbar", "Al-Anbar"),
                    ("al_basra", "Al-Basra"),
                    ("al_muthanna", "Al-Muthanna"),
                    ("an_najaf", "An-Najaf"),
                    ("al_qadisiyah", "Al-Qadisiyah"),
                    ("al_sulaymaniyah", "Al-Sulaymaniyah"),
                    ("babil", "Babil"),
                    ("baghdad", "Baghdad"),
                    ("dhi_qar", "Dhi-Qar"),
                    ("dyala", "Dyala"),
                    ("dohuk", "Dohuk"),
                    ("erbil", "Erbil"),
                    ("karbala", "Karbala"),
                    ("kirkuk", "Kirkuk"),
                    ("maysan", "Maysan"),
                    ("ninawa", "Ninawa"),
                    ("salah_ad_din", "Salah-ad-Din"),
                    ("wasit", "Wasit"),
                ],
                default="",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(
                choices=[("iraq", "Iraq")], default="", max_length=100
            ),
            preserve_default=False,
        ),
    ]
