# Generated by Django 4.1 on 2022-11-25 16:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_remove_order_address_2_order_city_order_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="order_no",
        ),
    ]
