# Generated by Django 4.1 on 2022-11-27 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_remove_order_order_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
