# Generated by Django 4.1 on 2023-06-15 20:27

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_order_notes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="orderline",
            options={"ordering": ["seq"], "verbose_name_plural": "Order Lines"},
        ),
        migrations.AddField(
            model_name="orderline",
            name="seq",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="order",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="create`d",
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="create`d",
            ),
        ),
        migrations.AlterField(
            model_name="supportticket",
            name="created",
            field=model_utils.fields.AutoCreatedField(
                default=django.utils.timezone.now,
                editable=False,
                verbose_name="create`d",
            ),
        ),
    ]
