# Generated by Django 5.0.2 on 2024-02-17 23:34

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0011_alter_order_created_alter_orderline_created_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="country",
        ),
        migrations.RemoveField(
            model_name="order",
            name="email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="full_name",
        ),
        migrations.RemoveField(
            model_name="order",
            name="is_wholesale",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone_2",
        ),
        migrations.AddField(
            model_name="order",
            name="approved_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="status", null=True, when={"approved"}
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="approved_by",
            field=models.ForeignKey(
                blank=True,
                db_column="approved_by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_approved_by",
                related_query_name="%(class)s_approved_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="approved_notes",
            field=models.TextField(blank=True, verbose_name="Approved Notes"),
        ),
        migrations.AddField(
            model_name="order",
            name="rejected_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="status", null=True, when={"rejected"}
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                db_column="rejected_by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_rejected_by",
                related_query_name="%(class)s_rejected_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="rejected_notes",
            field=models.TextField(blank=True, verbose_name="Rejected Notes"),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Status",
            ),
        ),
        migrations.CreateModel(
            name="OrderLineKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss_created_by",
                        related_query_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Order Lines Key",
            },
        ),
    ]
