# Generated by Django 5.0.2 on 2024-02-17 23:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_remove_order_city_remove_order_country_and_more"),
        ("products", "0006_productkey_delete_productkeys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlinekey",
            name="key",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_line_keys",
                related_query_name="order_line_key",
                to="products.productkey",
            ),
        ),
        migrations.AddField(
            model_name="orderlinekey",
            name="order_line",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_line_keys",
                related_query_name="order_line_key",
                to="orders.orderline",
            ),
        ),
        migrations.AddField(
            model_name="orderlinekey",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_updated_by",
                related_query_name="%(class)s_updated_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
