# Generated by Django 5.0.2 on 2024-02-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_orderlinekey_key_orderlinekey_order_line_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=None, max_digits=26),
            preserve_default=False,
        ),
    ]
