# Generated by Django 5.0.2 on 2024-03-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_orderline_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_amount_from_wallet",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Paid Amount From Wallet",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="use_wallet",
            field=models.BooleanField(default=False),
        ),
    ]
