# Generated by Django 5.0.2 on 2024-03-13 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_order_paid_amount_from_wallet_order_use_wallet"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total Price"
            ),
        ),
    ]
