# Generated by Django 5.0.2 on 2024-03-19 01:51

import django.db.models.deletion
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0016_order_total_price"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="returned_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="status", null=True, when={"returned"}
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="returned_by",
            field=models.ForeignKey(
                blank=True,
                db_column="returned_by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_returned_by",
                related_query_name="%(class)s_returned_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("returned", "Returned"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
