# Generated by Django 5.0.2 on 2024-03-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0017_order_returned_at_order_returned_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="paid_amount_from_wallet",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=26,
                verbose_name="Paid Amount From Wallet",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                decimal_places=0, default=0, max_digits=26, verbose_name="Total Price"
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="unit_price",
            field=models.DecimalField(decimal_places=0, max_digits=26),
        ),
    ]
