# Generated by Django 5.0.2 on 2024-03-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0018_alter_order_paid_amount_from_wallet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlinekey",
            name="other_info",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
