# Generated by Django 5.0.2 on 2024-03-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0019_orderlinekey_other_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
