# Generated by Django 5.0.2 on 2024-03-25 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0020_order_is_viewed"),
        ("products", "0022_alter_product_keys_users_count_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="keys_users_count",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_lines",
                related_query_name="order_line",
                to="products.keyuserscount",
            ),
        ),
        migrations.AddField(
            model_name="orderline",
            name="keys_validity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_lines",
                related_query_name="order_line",
                to="products.keyvalidity",
            ),
        ),
    ]
