# Generated by Django 5.0.2 on 2024-03-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0021_orderline_keys_users_count_orderline_keys_validity"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default="", max_length=50, unique=True, verbose_name="Order Number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("zain_cash", "Zain Cash"),
                    ("fast_pay", "Fast Pay"),
                    ("credit_card", "Credit Card"),
                ],
                default="cash",
                max_length=50,
                verbose_name="Payment Method",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Payment Status",
            ),
        ),
    ]
