# Generated by Django 5.0.2 on 2024-03-29 16:51

from django.db import migrations, models

import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0022_order_order_number_order_payment_method_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(
                default=orders.models.get_next_order_number,
                max_length=50,
                unique=True,
                verbose_name="Order Number",
            ),
        ),
    ]
