# Generated by Django 5.0.2 on 2024-03-29 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0023_alter_order_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="transaction_url",
            field=models.URLField(blank=True),
        ),
    ]
