# Generated by Django 5.0.2 on 2024-03-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0024_order_transaction_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="zain_cash_transaction_id",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
