# Generated by Django 5.0.2 on 2024-03-30 21:20

import django.db.models.deletion
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0025_order_zain_cash_transaction_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                monitor="payment_status",
                null=True,
                when={"paid"},
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_by",
            field=models.ForeignKey(
                blank=True,
                db_column="paid_by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_paid_by",
                related_query_name="%(class)s_paid_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_failed_at",
            field=model_utils.fields.MonitorField(
                blank=True,
                default=None,
                monitor="payment_status",
                null=True,
                when={"failed"},
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_failed_by",
            field=models.ForeignKey(
                blank=True,
                db_column="payment_failed_by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_payment_failed_by",
                related_query_name="%(class)s_payment_failed_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
