# Generated by Django 5.0.2 on 2024-03-31 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0026_order_paid_at_order_paid_by_order_payment_failed_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="zain_cash_transaction_id",
            new_name="transaction_id",
        ),
    ]
