# Generated by Django 5.0.2 on 2024-04-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0027_rename_zain_cash_transaction_id_order_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="card_holder",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="order",
            name="masked_card_number",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
