# Generated by Django 5.0.2 on 2024-04-05 11:46

import django.db.models.deletion
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0028_order_card_holder_order_masked_card_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="canceled_at",
            field=model_utils.fields.MonitorField(
                blank=True, default=None, monitor="status", null=True, when={"canceled"}
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="canceled_by",
            field=models.ForeignKey(
                blank=True,
                db_column="canceled_by",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)ss_canceled_by",
                related_query_name="%(class)s_canceled_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("returned", "Returned"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
