# Generated by Django 5.0.2 on 2024-04-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0029_order_canceled_at_order_canceled_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderline",
            name="keys_users_count",
        ),
        migrations.RemoveField(
            model_name="orderline",
            name="keys_validity",
        ),
    ]
