# Generated by Django 5.0.2 on 2024-04-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0030_remove_orderline_keys_users_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_id",
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
