# Generated by Django 5.0.2 on 2024-05-02 14:22

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0031_alter_order_transaction_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="fib_payment_valid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="qr_code",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.utils.get_upload_path
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="readable_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("zain_cash", "Zain Cash"),
                    ("fast_pay", "Fast Pay"),
                    ("credit_card", "Credit Card"),
                    ("fib", "FIB"),
                ],
                default="cash",
                max_length=50,
                verbose_name="Payment Method",
            ),
        ),
    ]
