# Generated by Django 5.0.2 on 2024-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0032_order_fib_payment_valid_until_order_qr_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="transaction_url",
            field=models.URLField(blank=True, max_length=550),
        ),
    ]
