# Generated by Django 5.0.2 on 2024-05-02 14:45

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0034_alter_order_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="qr_code",
            field=models.ImageField(
                blank=True,
                max_length=1000,
                null=True,
                upload_to=core.utils.get_upload_path,
            ),
        ),
    ]
