# Generated by Django 5.0.2 on 2024-05-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0037_alter_order_qr_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="qr_code",
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
