# Generated by Django 4.2.13 on 2024-12-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0038_alter_order_qr_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="product_image",
            field=models.URLField(blank=True, null=True),
        ),
    ]
