# Generated by Django 4.2.13 on 2024-12-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0039_orderline_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="is_wholesale",
            field=models.BooleanField(default=False),
        ),
    ]
