# Generated by Django 4.2.13 on 2025-01-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_notification_related_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="hidden",
            field=models.BooleanField(
                default=True, verbose_name="Is the notification hidden?"
            ),
        ),
    ]
