# Generated by Django 4.2.13 on 2025-01-14 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notification_hidden"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="hidden",
            field=models.BooleanField(
                default=False, verbose_name="Is the notification hidden?"
            ),
        ),
    ]
