# Generated by Django 4.2.13 on 2025-03-16 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_alter_notification_hidden"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="related_object_content_type",
            new_name="content_type",
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="related_object_id",
            new_name="object_id",
        ),
    ]
