# Generated by Django 5.0.2 on 2024-02-15 23:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productsection",
            options={
                "ordering": ["seq", "created"],
                "verbose_name_plural": "Product Sections",
            },
        ),
    ]
