# Generated by Django 5.0.2 on 2024-02-17 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_categoryslider_slider_subcategoryslider_delete_deal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categoryslider",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_slider_items",
                related_query_name="category_slider_item",
                to="products.category",
            ),
        ),
        migrations.AlterField(
            model_name="subcategoryslider",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sub_category_slider_items",
                related_query_name="sub_category_slider_item",
                to="products.subcategory",
            ),
        ),
    ]
