# Generated by Django 5.0.2 on 2024-02-17 02:42

import django.db.models.deletion
import django.utils.timezone
import django_lifecycle.mixins
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_categoryslider_category_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_key_product",
            field=models.BooleanField(
                default=False, help_text="is this product a key product?"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="keys_qty",
            field=models.PositiveIntegerField(
                blank=True, default=None, null=True, verbose_name="Keys Quantity"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="qty",
            field=models.PositiveIntegerField(default=0, verbose_name="Quantity"),
        ),
        migrations.CreateModel(
            name="ProductKeys",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("is_used", models.BooleanField(default=False)),
                (
                    "used_at",
                    model_utils.fields.MonitorField(
                        blank=True,
                        default=None,
                        monitor="is_used",
                        null=True,
                        when={True},
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="created_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss_created_by",
                        related_query_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_keys",
                        related_query_name="product_key",
                        to="products.product",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss_updated_by",
                        related_query_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Product Keys",
                "ordering": ["id"],
            },
            bases=(django_lifecycle.mixins.LifecycleModelMixin, models.Model),
        ),
    ]
