# Generated by Django 5.0.2 on 2024-02-18 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_alter_transaction_transaction_type"),
        ("products", "0007_productwholesalepricing"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="productwholesalepricing",
            unique_together={("product", "wholesale_user_type")},
        ),
    ]
