# Generated by Django 5.0.2 on 2024-02-18 23:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0008_alter_productwholesalepricing_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="wholesale_old_price",
        ),
        migrations.RemoveField(
            model_name="product",
            name="wholesale_price",
        ),
    ]
