# Generated by Django 5.0.2 on 2024-02-28 18:57

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_remove_product_wholesale_old_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subcategory",
            name="image_file",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.utils.get_upload_path
            ),
        ),
    ]
