# Generated by Django 5.0.2 on 2024-02-29 14:39

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_subcategory_image_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_file",
            field=models.ImageField(
                blank=True, null=True, upload_to=core.utils.get_upload_path
            ),
        ),
    ]
