# Generated by Django 5.0.2 on 2024-03-12 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_category_image_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["seq"], "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["seq"], "verbose_name_plural": "Products"},
        ),
        migrations.AlterModelOptions(
            name="subcategory",
            options={"ordering": ["seq"], "verbose_name_plural": "Sub Categories"},
        ),
        migrations.AddField(
            model_name="category",
            name="seq",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="seq",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="seq",
            field=models.IntegerField(default=0),
        ),
    ]
