# Generated by Django 5.0.2 on 2024-03-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cashback_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=26, null=True
            ),
        ),
    ]
