# Generated by Django 5.0.2 on 2024-03-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_product_cashback_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="cashback_amount",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=26, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=26, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=26),
        ),
        migrations.AlterField(
            model_name="productwholesalepricing",
            name="price",
            field=models.DecimalField(decimal_places=0, max_digits=26),
        ),
    ]
