# Generated by Django 5.0.2 on 2024-03-19 02:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_alter_product_cashback_amount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="product",
            name="description_ar",
            field=models.TextField(blank=True),
        ),
    ]
