# Generated by Django 5.0.2 on 2024-03-19 02:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0015_product_description_product_description_ar"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="keys_users_count",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="keys_validity",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100),
                blank=True,
                null=True,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="productkey",
            name="key_users_count",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="productkey",
            name="key_validity",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
