# Generated by Django 5.0.2 on 2024-03-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_product_keys_users_count_product_keys_validity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="offer_products",
            field=models.ManyToManyField(blank=True, to="products.product"),
        ),
    ]
