# Generated by Django 5.0.2 on 2024-03-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0017_product_offer_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_offer_product",
            field=models.BooleanField(default=False),
        ),
    ]
