# Generated by Django 5.0.2 on 2024-03-22 07:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0018_product_is_offer_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="is_offer_product",
        ),
    ]
