# Generated by Django 5.0.2 on 2024-03-25 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0019_remove_product_is_offer_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productkey",
            name="is_viewed",
            field=models.BooleanField(default=False),
        ),
    ]
