# Generated by Django 5.0.2 on 2024-03-25 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0021_remove_product_keys_users_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="keys_users_count_options",
            field=models.ManyToManyField(to="products.keyuserscount"),
        ),
        migrations.AlterField(
            model_name="product",
            name="keys_validity_options",
            field=models.ManyToManyField(to="products.keyvalidity"),
        ),
        migrations.AlterField(
            model_name="productkey",
            name="users_count",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_keys",
                related_query_name="product_key",
                to="products.keyuserscount",
            ),
        ),
        migrations.AlterField(
            model_name="productkey",
            name="validity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_keys",
                related_query_name="product_key",
                to="products.keyvalidity",
            ),
        ),
    ]
