# Generated by Django 5.0.2 on 2024-03-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0022_alter_product_keys_users_count_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="keyvalidity",
            name="validity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="keyvalidity",
            name="validity_unit",
            field=models.CharField(
                choices=[
                    ("day", "Day"),
                    ("week", "Week"),
                    ("month", "Month"),
                    ("year", "Year"),
                    ("lifetime", "Lifetime"),
                ],
                max_length=50,
                verbose_name="Validity Unit",
            ),
        ),
    ]
