# Generated by Django 5.0.2 on 2024-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0023_alter_keyvalidity_validity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="tutorial",
            field=models.URLField(blank=True, null=True),
        ),
    ]
