# Generated by Django 5.0.2 on 2024-04-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0024_product_tutorial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_options",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_option_product",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="options_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                related_query_name="+",
                to="products.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="offer_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="+",
                related_query_name="+",
                to="products.product",
            ),
        ),
    ]
