# Generated by Django 5.0.2 on 2024-04-06 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0025_product_has_options_product_is_option_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="has_options",
        ),
        migrations.RemoveField(
            model_name="product",
            name="is_option_product",
        ),
        migrations.RemoveField(
            model_name="product",
            name="keys_users_count_options",
        ),
        migrations.RemoveField(
            model_name="product",
            name="keys_validity_options",
        ),
        migrations.RemoveField(
            model_name="product",
            name="options_products",
        ),
        migrations.AddField(
            model_name="product",
            name="keys_users_count",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="+",
                to="products.keyuserscount",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="keys_validity",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="+",
                to="products.keyvalidity",
            ),
            preserve_default=False,
        ),
    ]
