# Generated by Django 5.0.2 on 2024-04-06 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0027_productoption"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="keys_users_count",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="+",
                to="products.keyuserscount",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="keys_validity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                related_query_name="+",
                to="products.keyvalidity",
            ),
        ),
    ]
