# Generated by Django 5.0.2 on 2024-04-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0028_alter_product_keys_users_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_options",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_option_product",
            field=models.BooleanField(default=False),
        ),
    ]
