# Generated by Django 5.0.2 on 2024-04-06 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0029_product_has_options_product_is_option_product"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productkey",
            name="users_count",
        ),
        migrations.RemoveField(
            model_name="productkey",
            name="validity",
        ),
    ]
