# Generated by Django 5.0.2 on 2024-04-06 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0030_remove_productkey_users_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoption",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="option_of",
                related_query_name="option_of",
                to="products.product",
            ),
        ),
    ]
