# Generated by Django 5.0.2 on 2024-04-17 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0031_alter_productoption_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="download_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
