# Generated by Django 4.2.13 on 2024-05-30 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0032_product_download_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_discounted",
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
