# Generated by Django 4.2.13 on 2024-09-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0033_product_is_discounted"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
