# Generated by Django 4.2.13 on 2024-12-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0034_product_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="number_of_keys_to_send_notification",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Number of Keys to Send Notification"
            ),
        ),
    ]
