# Generated by Django 4.2.13 on 2024-12-27 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0035_product_number_of_keys_to_send_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="inactive",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
