# Generated by Django 4.2.13 on 2024-12-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0036_product_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("inactive", "Inactive")],
                default="active",
                max_length=50,
                verbose_name="Status",
            ),
        ),
    ]
