# Generated by Django 4.2.13 on 2025-01-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0037_alter_product_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="search_status",
            field=models.CharField(default="Good", max_length=255),
        ),
    ]
