# Generated by Django 4.2.13 on 2025-03-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0038_product_search_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
