# Generated by Django 4.2.13 on 2025-03-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0039_category_is_deleted_subcategory_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
