# Generated by Django 4.2.13 on 2025-04-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0040_company_is_deleted"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="keyuserscount",
            options={"ordering": ["count"], "verbose_name_plural": "Key Users Count"},
        ),
    ]
