# Generated by Django 4.2.13 on 2025-04-15 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0041_alter_keyuserscount_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="keyvalidity",
            options={"ordering": ["validity"], "verbose_name_plural": "Key Validity"},
        ),
    ]
