# Generated by Django 4.2.13 on 2025-06-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0043_product_is_special_offer_specialoffer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="specialoffer",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="specialoffer",
            name="title_ar",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
